apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: prism
data:
  JAEGER_SERVICE_NAME: "prism"
  JAEGER_SAMPLER_TYPE: "const"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_AGENT_HOST: "jaeger-agent"
  JAEGER_AGENT_PORT: "6831"
